# =============================================================================
# Yggdrasil Integration — Shared Config (all environments)
# =============================================================================
image:
  repository: crocohub/yggdrasil-integration
  pullPolicy: IfNotPresent

service:
  name: yggdrasil-integration-service
  type: ClusterIP
  port: 8080
  targetPort: 8080

serviceAccount:
  create: true

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /

extraPorts:
  - name: debug
    containerPort: 5005

serviceMonitor:
  enabled: true
  path: /actuator/prometheus
  interval: 10s

deploymentStrategy:
  type: "RollingUpdate"
  rollingUpdate:
    maxSurge: "25%"
    maxUnavailable: "25%"

lifecycle:
  postStart:
    exec:
      command: ["/bin/bash", "-c", "update-ca-certificates"]

volumes:
  - name: my-certs-for-services
    secret:
      secretName: my-certs-for-services
  - name: yggdrasil-game-list-configmap
    configMap:
      name: yggdrasil-game-list-configmap

volumeMounts:
  - name: my-certs-for-services
    mountPath: /usr/local/share/ca-certificates
    readOnly: true
  - name: yggdrasil-game-list-configmap
    mountPath: /home
    readOnly: true

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: "app.kubernetes.io/name"
                operator: "In"
                values:
                  - "yggdrasil-integration"
          topologyKey: "kubernetes.io/hostname"

livenessProbe:
  initialDelaySeconds: 15
  periodSeconds: 10
  httpGet:
    path: /actuator/health/liveness
    port: 8080

readinessProbe:
  initialDelaySeconds: 15
  periodSeconds: 15
  httpGet:
    path: /actuator/health/readiness
    port: 8080
