{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "service-template.fullname" . }}-monitor
  labels:
    {{- include "service-template.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "service-template.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    any: true
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
