apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-prod-co
  namespace: argocd
  labels:
    environment: prod
    cluster: co
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: "https://github.com/iraklikairakli/app-of-app.git"
        revision: HEAD
        directories:
          - path: "services/*"
            exclude: false
          - path: "services/_*"
            exclude: true
  template:
    metadata:
      name: "prod-co-{{ .path.basename }}"
      labels:
        app.kubernetes.io/part-of: app-of-apps
        environment: prod
        cluster: co
    spec:
      project: integrations
      destination:
        server: "https://10.4.12.200:6443"
        namespace: default
      source:
        repoURL: "https://github.com/iraklikairakli/app-of-app.git"
        targetRevision: HEAD
        path: chart
        helm:
          valueFiles:
            - "../environments/prod-co.yaml"
            - "../{{ .path.path }}/base.yaml"
            - "../{{ .path.path }}/prod.yaml"
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas
