apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-prod-cluster-1
  namespace: argocd
  labels:
    environment: prod
    cluster: prod-1
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: "https://github.com/iraklikairakli/app-of-app.git"
        revision: HEAD
        directories:
          - path: "services/*"
            exclude: false
          - path: "services/_*"
            exclude: true
  template:
    metadata:
      name: "{{ .path.basename }}-prod-1"
      labels:
        app.kubernetes.io/part-of: app-of-apps
        environment: prod
        cluster: prod-1
    spec:
      project: default
      destination:
        server: "https://prod-1.k8s.example.com"
        namespace: production
      source:
        repoURL: "https://github.com/iraklikairakli/app-of-app.git"
        targetRevision: HEAD
        path: chart
        helm:
          valueFiles:
            - "../environments/prod-cluster-1.yaml"
            - "../{{ .path.path }}/base.yaml"
            - "../{{ .path.path }}/prod.yaml"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas
